//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrenRegestratie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engineer
    {
        public Engineer()
        {
            this.Regestraties = new HashSet<Regestratie>();
            this.user_taak = new HashSet<user_taak>();
        }
    
        public int userID { get; set; }
        public string voornaam { get; set; }
        public string achternaam { get; set; }
        public string gebruikersnaam { get; set; }
        public string wachtwoord { get; set; }
        public bool permissie { get; set; }
        public byte[] foto { get; set; }
        public bool actief { get; set; }
    
        public virtual ICollection<Regestratie> Regestraties { get; set; }
        public virtual ICollection<user_taak> user_taak { get; set; }
    }
}
