//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrenRegestratie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engineer
    {
        public Engineer()
        {
            this.Regestratie = new HashSet<Regestratie>();
        }
    
        public int userID { get; set; }
        public string voornaam { get; set; }
        public string achternaam { get; set; }
        public string gebruikersnaam { get; set; }
        public string wachtwoord { get; set; }
        public bool permissie { get; set; }
        public byte[] foto { get; set; }
    
        public virtual ICollection<Regestratie> Regestratie { get; set; }
    }
}
