//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrenRegestratie
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_taak
    {
        public user_taak()
        {
            this.Regestraties = new HashSet<Regestratie>();
        }
    
        public int userID { get; set; }
        public int taakID { get; set; }
        public int projectID { get; set; }
    
        public virtual Engineer Engineer { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<Regestratie> Regestraties { get; set; }
        public virtual taak taak { get; set; }
    }
}
